# coding: utf-8

"""
    Aliz AIP REST API

    AIP Workspace API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aip-support@aliz.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from aliz.aip.sdk.models.create_template_dto import CreateTemplateDto  # noqa: F401,E501

class CreateBaseTemplateDto(CreateTemplateDto):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cookie_cutter_content': 'dict(str, object)'
    }
    if hasattr(CreateTemplateDto, "swagger_types"):
        swagger_types.update(CreateTemplateDto.swagger_types)

    attribute_map = {
        'cookie_cutter_content': 'cookieCutterContent'
    }
    if hasattr(CreateTemplateDto, "attribute_map"):
        attribute_map.update(CreateTemplateDto.attribute_map)

    def __init__(self, cookie_cutter_content=None, *args, **kwargs):  # noqa: E501
        """CreateBaseTemplateDto - a model defined in Swagger"""  # noqa: E501
        self._cookie_cutter_content = None
        self.discriminator = None
        if cookie_cutter_content is not None:
            self.cookie_cutter_content = cookie_cutter_content
        CreateTemplateDto.__init__(self, *args, **kwargs)

    @property
    def cookie_cutter_content(self):
        """Gets the cookie_cutter_content of this CreateBaseTemplateDto.  # noqa: E501


        :return: The cookie_cutter_content of this CreateBaseTemplateDto.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._cookie_cutter_content

    @cookie_cutter_content.setter
    def cookie_cutter_content(self, cookie_cutter_content):
        """Sets the cookie_cutter_content of this CreateBaseTemplateDto.


        :param cookie_cutter_content: The cookie_cutter_content of this CreateBaseTemplateDto.  # noqa: E501
        :type: dict(str, object)
        """

        self._cookie_cutter_content = cookie_cutter_content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateBaseTemplateDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBaseTemplateDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
