# coding: utf-8

"""
    Aliz AIP REST API

    AIP Workspace API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aip-support@aliz.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeleteWorkspaceDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_to_be_deleted_in_gcp': 'list[str]',
        'remove_git_repository': 'bool'
    }

    attribute_map = {
        'project_to_be_deleted_in_gcp': 'projectToBeDeletedInGcp',
        'remove_git_repository': 'removeGitRepository'
    }

    def __init__(self, project_to_be_deleted_in_gcp=None, remove_git_repository=None):  # noqa: E501
        """DeleteWorkspaceDto - a model defined in Swagger"""  # noqa: E501
        self._project_to_be_deleted_in_gcp = None
        self._remove_git_repository = None
        self.discriminator = None
        if project_to_be_deleted_in_gcp is not None:
            self.project_to_be_deleted_in_gcp = project_to_be_deleted_in_gcp
        if remove_git_repository is not None:
            self.remove_git_repository = remove_git_repository

    @property
    def project_to_be_deleted_in_gcp(self):
        """Gets the project_to_be_deleted_in_gcp of this DeleteWorkspaceDto.  # noqa: E501


        :return: The project_to_be_deleted_in_gcp of this DeleteWorkspaceDto.  # noqa: E501
        :rtype: list[str]
        """
        return self._project_to_be_deleted_in_gcp

    @project_to_be_deleted_in_gcp.setter
    def project_to_be_deleted_in_gcp(self, project_to_be_deleted_in_gcp):
        """Sets the project_to_be_deleted_in_gcp of this DeleteWorkspaceDto.


        :param project_to_be_deleted_in_gcp: The project_to_be_deleted_in_gcp of this DeleteWorkspaceDto.  # noqa: E501
        :type: list[str]
        """

        self._project_to_be_deleted_in_gcp = project_to_be_deleted_in_gcp

    @property
    def remove_git_repository(self):
        """Gets the remove_git_repository of this DeleteWorkspaceDto.  # noqa: E501


        :return: The remove_git_repository of this DeleteWorkspaceDto.  # noqa: E501
        :rtype: bool
        """
        return self._remove_git_repository

    @remove_git_repository.setter
    def remove_git_repository(self, remove_git_repository):
        """Sets the remove_git_repository of this DeleteWorkspaceDto.


        :param remove_git_repository: The remove_git_repository of this DeleteWorkspaceDto.  # noqa: E501
        :type: bool
        """

        self._remove_git_repository = remove_git_repository

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeleteWorkspaceDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeleteWorkspaceDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
