# coding: utf-8

"""
    Aliz AIP REST API

    AIP Workspace API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aip-support@aliz.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GitSettingsDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'provisioning_branch': 'str'
    }

    attribute_map = {
        'provisioning_branch': 'provisioningBranch'
    }

    def __init__(self, provisioning_branch=None):  # noqa: E501
        """GitSettingsDto - a model defined in Swagger"""  # noqa: E501
        self._provisioning_branch = None
        self.discriminator = None
        if provisioning_branch is not None:
            self.provisioning_branch = provisioning_branch

    @property
    def provisioning_branch(self):
        """Gets the provisioning_branch of this GitSettingsDto.  # noqa: E501


        :return: The provisioning_branch of this GitSettingsDto.  # noqa: E501
        :rtype: str
        """
        return self._provisioning_branch

    @provisioning_branch.setter
    def provisioning_branch(self, provisioning_branch):
        """Sets the provisioning_branch of this GitSettingsDto.


        :param provisioning_branch: The provisioning_branch of this GitSettingsDto.  # noqa: E501
        :type: str
        """

        self._provisioning_branch = provisioning_branch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GitSettingsDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GitSettingsDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
