# coding: utf-8

"""
    Aliz AIP REST API

    AIP Workspace API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aip-support@aliz.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetricValueDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'yvalue': 'float',
        'xvalue': 'str'
    }

    attribute_map = {
        'yvalue': 'yvalue',
        'xvalue': 'xvalue'
    }

    def __init__(self, yvalue=None, xvalue=None):  # noqa: E501
        """MetricValueDto - a model defined in Swagger"""  # noqa: E501
        self._yvalue = None
        self._xvalue = None
        self.discriminator = None
        if yvalue is not None:
            self.yvalue = yvalue
        if xvalue is not None:
            self.xvalue = xvalue

    @property
    def yvalue(self):
        """Gets the yvalue of this MetricValueDto.  # noqa: E501


        :return: The yvalue of this MetricValueDto.  # noqa: E501
        :rtype: float
        """
        return self._yvalue

    @yvalue.setter
    def yvalue(self, yvalue):
        """Sets the yvalue of this MetricValueDto.


        :param yvalue: The yvalue of this MetricValueDto.  # noqa: E501
        :type: float
        """

        self._yvalue = yvalue

    @property
    def xvalue(self):
        """Gets the xvalue of this MetricValueDto.  # noqa: E501


        :return: The xvalue of this MetricValueDto.  # noqa: E501
        :rtype: str
        """
        return self._xvalue

    @xvalue.setter
    def xvalue(self, xvalue):
        """Sets the xvalue of this MetricValueDto.


        :param xvalue: The xvalue of this MetricValueDto.  # noqa: E501
        :type: str
        """

        self._xvalue = xvalue

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetricValueDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetricValueDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
