# coding: utf-8

"""
    Aliz AIP REST API

    AIP Workspace API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: aip-support@aliz.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServingModelVersionDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'version': 'str',
        'api_url': 'str',
        'model_registry_url': 'str',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'version': 'version',
        'api_url': 'apiUrl',
        'model_registry_url': 'modelRegistryUrl',
        'status': 'status'
    }

    def __init__(self, id=None, version=None, api_url=None, model_registry_url=None, status=None):  # noqa: E501
        """ServingModelVersionDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._version = None
        self._api_url = None
        self._model_registry_url = None
        self._status = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if version is not None:
            self.version = version
        if api_url is not None:
            self.api_url = api_url
        if model_registry_url is not None:
            self.model_registry_url = model_registry_url
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this ServingModelVersionDto.  # noqa: E501


        :return: The id of this ServingModelVersionDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServingModelVersionDto.


        :param id: The id of this ServingModelVersionDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this ServingModelVersionDto.  # noqa: E501


        :return: The version of this ServingModelVersionDto.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ServingModelVersionDto.


        :param version: The version of this ServingModelVersionDto.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def api_url(self):
        """Gets the api_url of this ServingModelVersionDto.  # noqa: E501


        :return: The api_url of this ServingModelVersionDto.  # noqa: E501
        :rtype: str
        """
        return self._api_url

    @api_url.setter
    def api_url(self, api_url):
        """Sets the api_url of this ServingModelVersionDto.


        :param api_url: The api_url of this ServingModelVersionDto.  # noqa: E501
        :type: str
        """

        self._api_url = api_url

    @property
    def model_registry_url(self):
        """Gets the model_registry_url of this ServingModelVersionDto.  # noqa: E501


        :return: The model_registry_url of this ServingModelVersionDto.  # noqa: E501
        :rtype: str
        """
        return self._model_registry_url

    @model_registry_url.setter
    def model_registry_url(self, model_registry_url):
        """Sets the model_registry_url of this ServingModelVersionDto.


        :param model_registry_url: The model_registry_url of this ServingModelVersionDto.  # noqa: E501
        :type: str
        """

        self._model_registry_url = model_registry_url

    @property
    def status(self):
        """Gets the status of this ServingModelVersionDto.  # noqa: E501


        :return: The status of this ServingModelVersionDto.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ServingModelVersionDto.


        :param status: The status of this ServingModelVersionDto.  # noqa: E501
        :type: str
        """
        allowed_values = ["PENDING", "READY", "FAILED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServingModelVersionDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServingModelVersionDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
